[assembler]
opcode_len = 5
instruction_len = 16

[[instructions]]
name = "CHILL"
opcode = 0
opcode_len = 7
arguments = ["@fill-9"]

[[instructions]]
name = "NFADD"
opcode = 0b0000100
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFSUB"
opcode = 0b0000101
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFAND"
opcode = 0b0000110
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFNOR"
opcode = 0b0000111
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFXOR"
opcode = 0b0001000
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NXNOR"
opcode = 0b0001001
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFPCA"
opcode = 0b0001010
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFPCS"
opcode = 0b0001011
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "NFMOV"
opcode = 0b0001100
opcode_len = 7
arguments = ["src_a-3", "@fill-3", "dest-3"]

[[instructions]]
name = "NFINC"
opcode = 0b0001101
opcode_len = 7
arguments = ["src_a-3", "@fill-3", "dest-3"]

[[instructions]]
name = "NFDEC"
opcode = 0b0001110
opcode_len = 7
arguments = ["src_a-3", "@fill-3", "dest-3"]

[[instructions]]
name = "NFRSH"
opcode = 0b0001111
opcode_len = 7
arguments = ["src_a-3", "@fill-3", "dest-3"]

[[instructions]]
name = "LDIMM"
opcode = 0b00100
opcode_len = 0
arguments = ["immediate-8", "dest-3"]

[[instructions]]
name = "FLADD"
opcode = 0b0010100
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLSUB"
opcode = 0b0010101
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLAAND"
opcode = 0b0010110
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLNOR"
opcode = 0b0010111
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLXOR"
opcode = 0b0011000
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLXNOR"
opcode = 0b0011001
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLPCA"
opcode = 0b0011010
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "FLPCS"
opcode = 0b0011011
opcode_len = 7
arguments = ["srd_a-3", "src_b-3", "dest-3"]

[[instructions]]
name = "BRNCH"
opcode = 0b01000
opcode_len = 0
arguments = ["@fill-1", "full_address-7", "condition-3"]

[[instructions]]
name = "DIMRD"
opcode = 0b01001
opcode_len = 0
arguments = ["memory_address-5", "@fill-3", "dest-3"]

[[instructions]]
name = "DIMUP"
opcode = 0b01010
opcode_len = 0
arguments = ["memory_address-5", "src-3", "@fill-3"]

[[instructions]]
name = "INMRD"
opcode = 0b01011
opcode_len = 0
arguments = ["op-2", "@fill-6", "dest-3"]

[[instructions]]
name = "INMUP"
opcode = 0b01100
opcode_len = 0
arguments = ["op-2", "@fill-3", "src-3", "@fill-3"]

[[instructions]]
name = "PTUPD"
opcode = 0b01101
opcode_len = 0
arguments = ["@fill-5", "src-3", "@fill-3"]

[[instructions]]
name = "HLTCL"
opcode = 0b01110
opcode_len = 0
arguments = ["U-1", "@fill-10"]

[[instructions]]
name = "INOUT"
opcode = 0b01111
opcode_len = 0
arguments = ["@fill-1", "io-1", "srd_a-3", "port-3", "dest-3"]

[[instructions]]
name = "PCALL"
opcode = 0b10000
opcode_len = 0
arguments = ["@fill-1", "full_address-7", "condition-3"]

[[instructions]]
name = "PRTRN"
opcode = 0b10001
opcode_len = 0
arguments = ["@fill-8", "condition-3"]









